repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
        args:
        -  --maxkb 500
    -   id: check-ast
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: detect-private-key
    -   id: check-toml
    -   id: pretty-format-json
        args:
        -  --autofix
        -  --no-ensure-ascii
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: []
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
    -   id: autoflake
        args:
        -  --remove-all-unused-imports
        -  --in-place
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
# Проверка секретов
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
# Заменять tabs на пробелы
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
    -   id: forbid-tabs
    -   id: remove-tabs
        args: [--whitespaces-count, '4']
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    -   id: black
        language_version: python3.10
